######### NORMAL OPERATION  ###########

### Read all films
GET http://localhost:3001/films

### Read film identified by 2
GET http://localhost:3001/films/2

### Create a film
POST http://localhost:3001/films
Content-Type: application/json

{
    "title":"Magic Green",
    "budget":"10 euros"
}

### Update the film identified by 2
PUT http://localhost:3001/films/1
Content-Type: application/json

{
    "title":"OSS 117 2"
}

### Delete film identified by 2
DELETE http://localhost:3001/films/1


######### ERROR OPERATION  ###########

### Read film which does not exists
GET http://localhost:3001/films/100

### Create a film without info for a property
POST http://localhost:3001/films
Content-Type: application/json

{
    "title":"",
    "duration":"1H30"
}

### Update for a film which does not exist
PUT http://localhost:3001/films/200
Content-Type: application/json

{
    "title":"Titanic"
}

### Update for a film which does not provide any info for a property
PUT http://localhost:3001/films/1
Content-Type: application/json

{
    "title":"Disney",
    "duration":"2H"
}